### ISSUE TITLE
Remove Converted to C# Indexers [Tracking Only] - No Actions

### ISSUE THREAD

**Issue by bakerboy448** [Prowlarr/Indexers#37]
Considering removing the below YMLs that have been converted to C#
(Reference https://github.com/Prowlarr/Prowlarr/blob/develop/src/NzbDrone.Core/IndexerVersions/IndexerDefinitionUpdateService.cs)

- [ ] - aither.yml https://github.com/Prowlarr/Prowlarr/commit/6b52dd6e7a0f9186535326e3f2eecdd8841174f9
- [ ] - animeworld.yml https://github.com/Prowlarr/Prowlarr/commit/e545e0a129586a734074a61dedbb00b93d556cc8
- [ ] - blutopia.yml https://github.com/Prowlarr/Prowlarr/commit/c1ab99a425952559cb18ca173eac2cfcf581fbdd
- [ ] - beyond-hd.yml https://github.com/Prowlarr/Prowlarr/commit/878e61e84bdce18eb46e81f60d49bdd6b75abdd2
- [ ] - beyond-hd-oneurl.yml https://github.com/Prowlarr/Prowlarr/commit/878e61e84bdce18eb46e81f60d49bdd6b75abdd2
- [ ] - desitorrents.yml https://github.com/Prowlarr/Prowlarr/commit/e4ef1c3af0598c1aa73555ee43e27e51ae42433f
- [ ] - danishbytes.yml https://github.com/Prowlarr/Prowlarr/commit/cf399ffdccf55742ad0cf093ba165fc421c31434
- [ ] - lat-team.yml https://github.com/Prowlarr/Prowlarr/commit/87650c83c6122c1a5ce6cc3585d30405be117788
- [ ] - hdbits.yml https://github.com/Prowlarr/Prowlarr/commit/2b920ac5f758dd5af9de59fe076c82281957ede7
- [ ] - shareisland.yml https://github.com/Prowlarr/Prowlarr/commit/f6a5f887ceb75e72a7751cc99551d9b82abcaa2b

[AB#1544](https://dev.azure.com/Servarr/7ab38f4e-5a57-4d70-84f4-94dd9bc5d6df/_workitems/edit/1544)

**Comment by bakerboy448** [comment]
N/A needed now with v3
